version: '3.7'
services:

  controller:
    build: ./controller
    image: connected:controller
    container_name: controller
    volumes:
      - ./scripts:/usr/share/scripts
      - keys:/usr/share/keys
    env_file:
      - ./.env

  client:
    build: ./client
    image: connected:client
    container_name: client_1
    volumes:
      - ./scripts:/usr/share/scripts
      - keys:/usr/share/keys
    ports:
      - "8080:8080"
    env_file:
      - ./.env

volumes:
  keys:
